homework5/website/auth.py
#authentification stuff
from flask import Blueprint, render_template, request, flash, redirect, url_for
from.models import User
from werkzeug.security import generate_password_hash, check_password_hash #secure password, we dont want to save the password as the password, we need to obfuscate it
from . import db
from flask_login import login_user, login_required, logout_user, current_user


auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST': #ask for the data from db
        email = request.form.get('email')
        password = request.form.get('password')
        
        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):#ask for password
                #flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                #flash('Incorrect password! Try again.', category='error')
                print('incorrect password')
        else:
            #flash('Email does not exist.', category='error', user=current_user)
            print('unknown email')
                
    return render_template("login.html", user=current_user)# text="testing", boolean=True you can pass variables here which is cool ex.bool=true

@auth.route('/logout')
@login_required #makes sure we can't access unless logged in
def logout():
    logout_user()
    return redirect(url_for('auth.login'))
    

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        username = request.form.get('firstName')
        password = request.form.get('password')
        passwordConfirm = request.form.get('passwordConfirm')

        user = User.query.filter_by(email=email).first()
        if user:
            flash('Email already exists.', category='error')
        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(username) < 2:
            flash('First name must be greater than 1 character.', category='error')
        elif password != passwordConfirm:
            flash('Passwords don\'t match.', category='error')
        elif len(password) < 7:
            flash('Password must be at least 7 characters.', category='error')
        else:
            new_user = User(email=email, username=username, password=generate_password_hash(password, method='scrypt'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.home'))

    return render_template("sign_up.html", user=current_user)

@auth.route('/change-password', methods=['GET', 'POST'])
@login_required
def change_password():
    if request.method == 'POST':
        current_password = request.form.get('current_password')
        new_password = request.form.get('new_password')
        confirm_password = request.form.get('confirm_password')

        user = current_user

        # Validate the current password
        if not user.check_password(current_password):
            flash('Incorrect current password. Password not changed.', category='error')
            return redirect(url_for('auth.change_password'))

        # Validate the new password and confirmation
        if len(new_password) < 7:
            flash('Password must be at least 7 characters.', category='error')
            return redirect(url_for('auth.change_password'))
        elif new_password != confirm_password:
            flash('Passwords do not match.', category='error')
            return redirect(url_for('auth.change_password'))

        # Update the password
        user.update_password(new_password)
        flash('Password changed successfully.', category='success')
        return redirect(url_for('.login'))  # Redirect to a suitable view after password change

    return render_template('changepass.html')

@auth.route('/delete-account', methods=['POST'])
@login_required
def delete_account():
    if request.method == 'POST':
        if 'user_id' in request.form:
            # Administrator is trying to delete a user
            if current_user.id == 1:
                user_id = int(request.form['user_id'])
                user_to_delete = User.query.get(user_id)

                if user_to_delete:
                    db.session.delete(user_to_delete)
                    db.session.commit()
                    flash(f'User with ID {user_id} deleted successfully.', category='success')
                else:
                    flash('User not found.', category='error')
            else:
                flash('You do not have permission to delete users.', category='error')
        else:
            # Regular user is trying to delete their own account
            user = current_user
            user.delete()
            logout_user()
            flash('Account deleted successfully.', category='success')

    return redirect(url_for('.lobotomy'))


@auth.route('/terms-of-service')
def tos():
    return render_template("TOS.html")

@auth.route('/account-issues')
def account_issues():
    return render_template("issues.html")

def get_all_users():
    users = User.query.all()
    return users

@auth.route('/profile')
@login_required
def user_profile():
    users = get_all_users()
    return render_template("profile.html", users=users, user=current_user)

@auth.route('/lobotomy')
def lobotomy():
    return render_template("lobotomy.html", user=current_user)

''' 
@auth.route('/save_score/<int:nivel>') #i am killing myself
@login_required
def save_score(nivel):
    print(f"Score received: {nivel}")
    if nivel > current_user.highest_score:
        current_user.highest_score = nivel
        db.session.commit()
        print("Score saved successfully.")
    else:
        print("Score not higher than current highest score.")
    return redirect(url_for('views.home'))
'''

homework5/website/templates/TOS.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
    <link href="static/styles.css" rel="stylesheet">
    <title>Terms of service</title>
</head>
<body style="color: white;">
    <div class="title">
        <h1>Terms of service!</h1>
        <label for='h1'>Read carefully</label>
    </div>
    
    <div>

    </div>
</body>
</html>

homework5/website/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
    />

    <title>{% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button
        class="navbar-toggler"
        type="button"
        data-toggle="collapse"
        data-target="#navbar"
      >
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <div class="navbar-nav">
          {% if user.is_authenticated %}
          <a class="nav-item nav-link" id="home" href="/">Home</a>
          <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
          {% else %}
          <a class="nav-item nav-link" id="login" href="/login">Login</a>
          <a class="nav-item nav-link" id="signUp" href="/sign-up">Sign Up</a>
          {% endif %}
        </div>
      </div>
    </nav>

    {% with messages = get_flashed_messages(with_categories=true) %} {% if
    messages %} {% for category, message in messages %} {% if category ==
    'error' %}
    <div class="alert alert-danger alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% else %}
    <div class="alert alert-success alter-dismissable fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endif %} {% endfor %} {% endif %} {% endwith %}

    <div class="container">{% block content %} {% endblock %}</div>
    <script
      src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
      integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
      crossorigin="anonymous"
    ></script>

{% block javascript %}
    <script type="text/javascript">
      function deleteNote(noteId) {
  fetch("/delete-note", {
    method: "POST",
    body: JSON.stringify({ noteId: noteId }),
  }).then((_res) => {
    window.location.href = "/";
  });
  }
</script>
{% endblock %}
  </body>
</html>

homework5/website/templates/changepass.html
<!-- change_password.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Change Password</title>
    <link href="static/styles.css" rel="stylesheet">
</head>
<body>
    <div class="registrationContainer">
        <form action="{{ url_for('auth.change_password') }}" method="post">
            <h1>Change Password</h1>
            <label for="current_password">Current Password:</label>
            <input class="boxSize" type="password" name="current_password" required><br>

            <label for="new_password">New Password:</label>
            <input class="boxSize" type="password" name="new_password" required><br>

            <label for="confirm_password">Confirm Password:</label>
            <input class="boxSize" type="password" name="confirm_password" required><br>
            <div>
                <button class="dontAsk" type="submit">Change Password</button>
            </div>
        </form>
    </div>
</body>
</html>

homework5/website/templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="static/styles.css" rel="stylesheet">
  <title>To-Do List App</title>
</head>

<body>
  <div class="registrationContainer">
      <h1 align="center">To do List:</h1>
      <ul class="list-group list-group-flush" id="notes">
        {% for note in user.notes %}
        <li class="list-group-item">
          {{ note.data }}
          <button type="button" class="close" onClick="deleteNote({{ note.id }})">
            <span aria-hidden="true">&times;</span>
          </button>
        </li>
        {% endfor %}
      </ul>
      <form method="POST">
        <textarea name="note" id="note" class="form-control"></textarea>
        <br />
        <div align="center">
          <button type="submit" class="btn btn-primary">Add</button>      
        </div>
        </div>
      </form>
  </div>
  <script src="static/script.js"></script>
</body>
</html>

homework5/website/templates/issues.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
    <link href="static/styles.css" rel="stylesheet">
    <title>Account issues</title>
</head>
<body style="color: white;">
    <div class="title">
        <h1>Issues with my account</h1>
        <label for='h1'>Can't do anything bout it lol</label>
    </div>
    
</body>
</html>

homework5/website/templates/lobotomy.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
  <!--<title>Get Lobotomised !</title>-->
  <link href="static/styles.css" rel="stylesheet">
</head>
<body style="color: white;">
    <h1 class="title">BAHAHAHAH LOBOTOMY SIMULATOR!</h1>
    <div style= "align-items: center; display: flex; justify-content: center;">
    <div id=":("></div>
    <!--<img class="registrationInputs" src="static/rat-spinning.gif" alt="Why do I feel this way">-->
    </div>
    <div style="align-items: center; display: flex; justify-content: center;">
    <p id="coolPar">You have been getting a lotobomy for:</p>
    <label for="coolPar" id="minutes">00</label>:<label id="seconds">00</label>
    </div>

    <div style= "align-items: center; display: flex; justify-content: center;">
    <button class="leButton"id="lobotomyButton" onclick="engageLobotomy()">Click to engage</button>
    </div>
    
    <script>
        (function titleScroller(text) {
            document.title = text;
            console.log(text);
            setTimeout(function () {
                titleScroller(text.substr(1) + text.substr(0, 1));
            }, 500);
        }("Get Lobotomised ! Get Lobotomised !"));
        /*stolen from here
        https://stackoverflow.com/questions/16354122/how-to-put-scrolling-text-in-title-tag*/
    </script>
	
	<script>
        function engageLobotomy(){
            document.getElementById('lobotomyButton').disabled = true;
            var audio = new Audio('static/freebird.mp3');
            audio.play();
            audio.loop = true;
            timerWhatever()
            imageWoosh()
        }

        function timerWhatever(){
            var minutesLabel = document.getElementById("minutes");
            var secondsLabel = document.getElementById("seconds");
            var totalSeconds = 0;
            setInterval(setTime, 1000);
    
            function setTime() {
            ++totalSeconds;
            secondsLabel.innerHTML = pad(totalSeconds % 60);
            minutesLabel.innerHTML = pad(parseInt(totalSeconds / 60));
            }
    
            function pad(val) {
            var valString = val + "";
            if (valString.length < 2) {
                return "0" + valString;
            } else {
                return valString;
            }
            }
            /*Stolen from here
            https://stackoverflow.com/questions/5517597/plain-count-up-timer-in-javascript*/
        }

        function imageWoosh(){

        var image = document.createElement("img");{
            image.src = "static/rat-spinning.gif";
            image.alt = "Why do I feel this way";
        }
        var imageContainer = document.getElementById(":(");{
            imageContainer.appendChild(image);
        }
    }   
	</script>
</body>
</html>

homework5/website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
    <link href="static/styles.css" rel="stylesheet">
    <title>Log in</title>
</head>
<body>
    <div class ="wholeDoc">
            
        <div class ="pageLogo">
            <img class ="pageLogo" src="static/logo.png" alt="logo">
        </div>
      
        <div id="error-container">
            <div id="emailError" class="error-message"></div>
            <div id="passwordError" class="error-message"></div>
            <div id="confirmPasswordError" class="error-message"></div>
        </div>
      
        <div class="registrationContainer">    
            <form id="login-form" method="POST">
                <label for="email">E-mail:</label>
                <input class="boxSize" type="email" id="email" name="email">
               
                <label for="email">Password:</label>
                <input class="boxSize" type="password" id ="password" name="password">
      
                <div > 
                    <p class="logInProblems">Login problems? Click <a href="/account-issues">here</a>!</p>
                    <p>Don't have an account? Click <a href="/sign-up">here</a>!</p>
                </div> 
                  
                <div>
                    <button type="submit" class="leButton">Login</button>
                </div>
            </form>
</body>
</html>

homework5/website/templates/profile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
    <link href="static/styles.css" rel="stylesheet">
    <title>Profile</title>
    <style>
        .flexbox{
          display: flex;
          
      }
      
      .user-pfp{
          max-width: 100%;
      }
      .user-info {
          margin-left: 20px;
      }
      
      .center-block {
        width: 30%; /* Adjust the width as needed */
        margin-left: auto;
        margin-right: auto;
      }

      .button{
        width: 64px;
        height: 64px;
      }
      
    </style>
</head>
<body style="color: white;">
    <h1 style="text-align: center;">This is your user profile!</h1>
    <div class="flexbox">
        
        <div class="center-block">
            <p>Hello {{ current_user.username }} !</p>
            <p>Your current email is: {{ current_user.email }}</p>
            {#<p>Your current user role is: {{ current_user.role }}</p>#}
            <p>Your unique User ID: {{ current_user.id }}</p>
            <p>Your current highest score is: {{ current_user.highest_score }}</p>
            
            <h3>Did you know ?</h3>
            <p>This websites has a lobotomy page! Click <a href="/lobotomy">here</a> to experience the lobotomy of your life!</p>

            <h3>Account settings</h2>
            <p>User related settings right here!</p>
            <button class="dontAsk"><a id="logout" href="/logout">Log out</a></button>
            <button class="dontAsk"><a href="/change-password">Change password</a></button>
            
            {% if current_user.id == 1 %}
                {# don't show the delete account button#}
            {% else %}
            <h3>Danger zone !</h3>
            <label>Account deletion is instant, don't come crying to me if you did it by accident</label>
            <form action="{{ url_for('auth.delete_account') }}" method="post">
                <button class="dontAsk" type="submit" onclick="epicQuestion()">Delete Account</button>
                <script>
                    /* yea I am not doing this rn it's 3:40 am
                     function epicQuestion(){
                   if (confirm('Are you sure you want to save this thing into the database?')) {
                        // Save it!
                        console.log('Thing was saved to the database.');
                      } else {
                        // Do nothing!
                        console.log('Thing was not saved to the database.');
                      }
                    }*/
                </script>
            </form>
            {%endif%}
    
            <div class="adminstuff">
                {% if current_user.id == 1 %}
                <h3>Admin Table</h2>
                <table border="2">
                    <tr>
                        <th>IDs</th>
                        <th>Username</th>
                        <th>Email</th>
                        <th>High score</th>
                        <th>Actions</th>
                    </tr>
                    {% for user in users %}
                        <tr id="user-{{ user.id }}">
                            <td>{{ user.id }}</td>
                            <td>{{ user.username }}</td>
                            <td>{{ user.email }}</td>
                            <td>{{ user.highest_score }}</td>
                            <td>
                                <button class="dontAsk" data-user-id="{{ user.id }}">Delete</button>
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            
                <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
                <script>
                    $(document).ready(function () {
                        $('button[data-user-id]').click(function () {
                            var userId = $(this).data('user-id');
                            var confirmation = confirm('Are you sure you want to delete this user?');
                    
                            if (confirmation) {
                                // Assuming you have a route or endpoint to handle user deletion
                                var deleteUrl = '/delete-account';
                    
                                // Include 'user_id' in the data for the AJAX request
                                var data = {
                                    user_id: userId
                                };
                    
                                // Send an AJAX request to delete the user
                                $.ajax({
                                    type: 'POST',
                                    url: deleteUrl,
                                    data: data,
                                    success: function () {
                                        // Remove the table row when the user is successfully deleted
                                        $('#user-' + userId).remove();
                                    },
                                    error: function () {
                                        alert('Failed to delete user.');
                                    }
                                });
                            }
                        });
                    });  
                </script>
            {% endif %}
            
            </table>
            </div>
        </div>
    </div>
</body>
</html>

homework5/website/templates/sign_up.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" type="image/x-icon" href="static/logo.ico" alt="logo">
    <link href="static/styles.css" rel="stylesheet">
    <title>Log in</title>
</head>
<body>
    <div class ="wholeDoc">
            
        <div class ="pageLogo">
            <img class ="pageLogo" src="static/logo.png" alt="logo">
        </div>
    
        <div id="error-container">
            <div id="emailError" class="error-message"></div>
            <div id="passwordError" class="error-message"></div>
            <div id="confirmPasswordError" class="error-message"></div>
        </div>
        
        <div class="registrationContainer">
            <form id="register-form" method="POST">
               <label for="inputUser">Username:</label>
                <input id="inputUser" class="boxSize" type="text" id="firstName" name="firstName">
                
                <label for="inputUser">Email:</label>
                <input class="boxSize" type="email" id="email" name="email" >
              
    
                <label for="email">Password:</label>
                <input class="boxSize" type="password" id="password" name="password" >
      
    
                <label for="email">Confirm Password:</label>
                <input class="boxSize" type="password" id="passwordConfirm" name="passwordConfirm" >
    
    
                <div>
                    <label for="TOS"><a href="/terms-of-service">Terms of Service</a></label>
                    <input type="checkbox" id="TOS" required>
                    <label for="TOS">Accept?</label>
                    <p>Already have an account? Click <a href="/login">here</a>!</p>
                </div>
    
                <div>
                    <button type="submit" class="leButton">Register</button>
                </div>
            </form>
        </div>
</body>
</html>